version: "3.8"
services:
  chat-app:
    hostname: backend
    restart: on-failure

    image: chat-management-app
    container_name: chat-management-container
    build: .
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
    networks:
      - my-network

networks:
  my-network:
    external: true